#!/usr/bin/env python3
"""Stage 2: turn gap_report.json into an ordered, patchable worklist.

Usage:
    python scripts/harness/plan_fixes.py [--gap-report .parity/gap_report.json]
                                         [--out .parity/worklist.json]
                                         [--top N]

Input : .parity/gap_report.json   (stage 1)
        botocore specs            (for spec shapes)
Output: .parity/worklist.json
    [
      {
        "test": "...", "service": "ssm", "bucket": "A1", "workstream": "WS1",
        "action": "de_stub" | "add_fields" | "fix_error_code" |
                  "implement_error_path" | "fix_shape" | "port_behavior",
        "ops": ["CreateOpsItem"],
        "group_key": "ssm/CreateOpsItem",       # items sharing this fix together
        "expected_tests_fixed": 4,
        "patch": {
            "files": ["crates/ssm/src/models.rs", "crates/ssm/src/handler.rs"],
            "dispatch_replace": {"file": "crates/ssm/src/handler.rs",
                                 "old": '"CreateOpsItem" => self.json_stub(&req, "OpsItemId"),',
                                 "new": '"CreateOpsItem" => self.create_ops_item(&req),'},
            "model_append": "  # generated: struct OpsItem {...}",
            "method_append": "  # generated: fn create_ops_item(...)",
            "spec_output_shape": {"OpsItemId": "string"},
            "moto_ref": "ssm/models.py:def create_ops_item",
        },
        "verify": "ENDPOINT_URL=http://127.0.0.1:4567 pytest tests/compatibility/test_ssm_compat.py::test_...",
        "est_lines": 40,
        "roi": 0.1
      }, ...
    ]

The patch fields model_append / method_append are TEMPLATE PLACEHOLDERS
produced here; the actual Rust is generated by gen_rust_op.py (stage 2b)
which reads the botocore output shape + the moto reference function and
emits concrete code. plan_fixes.py fixes the ORDER and the GROUPING so
the agent applies whole groups at once (one resource = one model + N ops).
"""
from __future__ import annotations

import argparse
import gzip
import json
import re
from collections import defaultdict
from glob import glob
from pathlib import Path

REPO = Path("/Users/jackdanger/www/robotocore")
RUST_REPO = Path("/Users/jackdanger/www/robotocore-rust")
BOTOCORE_DATA = REPO / ".venv/lib/python3.12/site-packages/botocore/data"

CRATE_NAME = {"logs": "cloudwatch-logs"}


def spec_output_shape(svc: str, op: str):
    """{wire_name: python_type} for the op's output structure, or None."""
    pat = str(BOTOCORE_DATA / svc / "*" / "service-2.json.gz")
    paths = glob(pat)
    if not paths:
        return None
    spec = json.load(gzip.open(paths[0]))
    opdef = spec["operations"].get(op, {})
    out = opdef.get("output", {}).get("shape")
    if not out:
        return {}
    shape = spec["shapes"][out]
    if shape.get("type") != "structure":
        return {out: shape.get("type")}
    outmap = {}
    for name, info in shape.get("members", {}).items():
        sub = spec["shapes"].get(info.get("shape"), {})
        wire = info.get("locationName", name)
        outmap[wire] = sub.get("type", "string")
    return outmap


def action_for(rec: dict):
    b = rec["bucket"]
    if b in ("A1", "A3") and rec["op_coverage"] in ("all_stubbed", "partial_stub") and rec["rust_stub_lines"]:
        return "de_stub"
    if b == "A1":
        return "add_fields"
    if b == "A3":
        return "fix_shape"
    if b == "A2":
        return "de_stub" if rec["rust_stub_lines"] else "fix_shape"
    if b in ("C2", "C3"):
        return "fix_error_code"
    if b in ("C1", "C5"):
        return "de_stub" if rec["rust_stub_lines"] else "implement_op"
    if b == "D":
        return "implement_error_path"
    if b == "G":
        return "de_stub" if rec["rust_stub_lines"] else "fix_id_format"
    if b in ("B", "B_assertion_other", "K"):
        return "port_behavior"
    return "port_behavior"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gap-report", default=str(RUST_REPO / ".parity/gap_report.json"))
    ap.add_argument("--out", default=str(RUST_REPO / ".parity/worklist.json"))
    ap.add_argument("--top", type=int, default=0, help="only keep top N groups")
    args = ap.parse_args()

    report = json.loads(Path(args.gap_report).read_text())
    # Group by the DEFINING OP per test:
    #  * de_stub/fix_error_code/add_fields/fix_shape on a stub -> the stubbed op
    #  * otherwise -> the test's first op (each such group fixes exactly 1 test)
    # This keeps expected_tests_fixed honest: a group only gets credit for
    # tests that actually depend on the op being fixed.
    groups = defaultdict(list)
    for svc in report["services"]:
        for rec in svc["tests"]:
            action = action_for(rec)
            stubbed_ops = [o for o in rec["ops"] if o in rec.get("rust_stub_lines", {})]
            if action in ("de_stub", "fix_error_code", "add_fields", "fix_shape",
                          "implement_op") and stubbed_ops:
                defining = stubbed_ops[0]
            elif rec["ops"]:
                defining = rec["ops"][0]
            else:
                defining = rec["test"]
            key = f"{svc['service']}/{defining}"
            rec2 = dict(rec, service=svc["service"], crate=svc["crate"], action=action,
                        group_key=key, defining_op=defining)
            groups[key].append(rec2)

    # Build group records
    out = []
    for key, recs in groups.items():
        svc = recs[0]["service"]
        crate = CRATE_NAME.get(svc, svc)
        op = recs[0].get("defining_op")
        if op in (None, recs[0]["test"]):
            op = None
        shape = spec_output_shape(svc, op) if op else None
        # estimate: model ~ 2 lines/field, method ~ 15 + 1/field, dispatch 1 line
        n_fields = len(shape) if shape else 0
        est_lines = max(20, 16 + 3 * n_fields)
        # only count tests that actually exercise the defining op
        n_fixed = sum(1 for r in recs if (r.get("defining_op") in r.get("ops", [])
                     or not r.get("ops")))
        # Calibrated effort: an op fix is one model + dispatch + tests that
        # share the op get a marginal cost of ~2 lines each (they usually pass
        # once the op is right). ROI = 1 / (0.4*est_lines + 0.6*max(1,n_fixed-1)*2)
        effort = 0.4 * est_lines + 0.6 * max(1, n_fixed - 1) * 2
        roi = n_fixed / effort
        testnames = sorted(r["test"] for r in recs)
        entry = {
            "group_key": key,
            "service": svc, "crate": crate, "op": op,
            "action": recs[0]["action"],
            "workstream": recs[0]["workstream"],
            "tests": testnames,
            "expected_tests_fixed": n_fixed,
            "est_lines": est_lines,
            "roi": round(roi, 4),
            "confidence": "high" if all(r["confidence"] == "high" for r in recs) else "medium",
            "spec_output_shape": shape,
            "moto_refs": {r["test"]: r.get("moto_refs") for r in recs},
            "verify": (f"ENDPOINT_URL=http://127.0.0.1:4567 python -m pytest "
                       f"tests/compatibility/test_{svc}_compat.py -k "
                       f"\"{' or '.join(t.split('::')[-1] for t in testnames[:5])}\""),
        }
        # dispatch replace for de_stub
        if entry["action"] == "de_stub" and op:
            lines = {r["test"]: r.get("rust_stub_lines", {}) for r in recs}
            ln = next((v for vals in lines.values() for v in vals.values()), None)
            if ln:
                f = RUST_REPO / "crates" / crate / "src" / "handler.rs"
                old = f.read_text().splitlines()[ln - 1].strip()
                snake = re.sub(r"(?<!^)(?=[A-Z])", "_", op).lower()
                entry["patch"] = {
                    "files": [f"crates/{crate}/src/handler.rs", f"crates/{crate}/src/models.rs"],
                    "dispatch_replace": {
                        "file": f"crates/{crate}/src/handler.rs", "line": ln,
                        "old": old,
                        "new": f'"{op}" => self.{snake}(&req),',
                    },
                }
        out.append(entry)

    out.sort(key=lambda e: (-e["roi"], e["group_key"]))
    if args.top:
        out = out[:args.top]
    Path(args.out).write_text(json.dumps(out, indent=2))
    print(f"wrote {args.out}  ({len(out)} groups, "
          f"{sum(e['expected_tests_fixed'] for e in out)} tests)")
    for e in out[:20]:
        print(f"  {e['roi']:6.3f}  {e['group_key']:40} {e['action']:20} fixes {e['expected_tests_fixed']}")


if __name__ == "__main__":
    main()
